const server = {
  MONGODB_CONNECTION_DONE: 'MONGODB_CONNECTION_DONE',
  MONGODB_CONNECTION_OPEN: 'MONGODB_CONNECTION_OPEN',
  MONGODB_CONNECTION_DISCONNECTED: 'MONGODB_CONNECTION_DISCONNECTED',
  MONGODB_CONNECTION_CLOSE: 'MONGODB_CONNECTION_CLOSE',
  START_CRON: 'START_CRON',
  MAIL_CLIENT_INITIALIZED: 'MAIL_CLIENT_INITIALIZED',
  SENDER_INITIALIZATION_DONE: 'SENDER_INITIALIZATION_DONE',
  MAIL_SENT: 'MAIL_SENT',
  SENDING_ALERT_DEBUG: 'SENDING_ALERT_DEBUG',
  SERVER_STARTED: 'SERVER_STARTED',
};

module.exports = server;
